### ISSUE TITLE
support ie10/11

### ISSUE THREAD

**Issue by hiyelbaz** [rogerpadilla/prouter#15]
```
<script src="https://unpkg.com/prouter/prouter.min.js"></script>
    <script>
        const router = prouter.browserRouter();
        router
            .use('/abc', function (req, res) {
                alert(1);
            })
            .use('*', function (req, res) {
                alert(2);
            })
        router.listen();
    </script>
```
`
router.push('/abc')
`
returns 2

change router:
`
.use('/abc', ..) => .use('abc',..)
`
now it returns 1

**Comment by rogerpadilla** [comment]
@hiyelbaz The '*' route is probably being executed since when 'router.listen()' is called there is not a match with '/abc', so that is why it executes '*' (in that case, it is like a default match for any path).

If that don't solves the issue, please re-open this and consider creating a plnkr/codepen where the issue can be replicated.
